# PATTERN  APPLICATION
# no "/" in PATTERN: host name; with "/": regexp over HOST[:PORT]/PATH (full match)
google.com           firefox.desktop
.example.net         Firefox
*.corp.example       chromium.desktop
yahoo\.org/image.*   chrome.desktop
localhost:8080/.*    /home/me/apps/devbrowser.desktop
